---
functional:
  - Пользователь должен иметь возможность зарегистрироваться и авторизоваться
  - Пользователь должен иметь возможность создать битву
  - Пользователь должен иметь возможность присоедениться к битве
  - Пользователь должен иметь возможность соревноваться с другим пользователем
  - Пользователь должен иметь возможность соревноваться с другом
  - Пользователь должен иметь возможность соревноваться с ботом
  - Пользователь должен иметь возможность выбирать уровень
  - Пользователь должен иметь возможность выбирать задачу
  - Пользователь должен иметь возможность фильтровать задачи по темам
  - Пользователь должен иметь возможность просматривать Rules & Details
  - Пользователь должен иметь возможность пользоваться чатом на главной странице
  - Пользователь должен иметь возможность просматривать таблицу лидеров (Hall of Fame)
  - Пользователь должен иметь возможность просматривать info других игроков
  - Код пользователя должен проверяться системой при клике на кнопку Run
  - Система должна определять победителя по результатам проверки кода
  - Интерфейс "Holopins" должен загружаться в user profile
  - При наведении на user в Hall of Fame должно появляться выпадающее меню с info
  - При выборе друга в выпадающем меню должен отображаться список друзей
  - В Settings должны работать все ссылки корректно
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Чат должен работать без необходимости обновлять страницу
  - Сообщения в чате должны отображаться сразу после отправки
  - Информация по турнирам должна отображаться корректно
  - Элементы интерфейса на страницы Clans должны отображаться корректно
