---
functional:
  - Пользователь должен иметь возможность создать битву
  - Пользователь должен иметь возможность присоедениться к битве
  - Пользователь должен иметь возможность соревноваться с другим пользователем
  - Пользователь должен иметь возможность соревноваться с другом
  - Пользователь должен иметь возможность соревноваться с ботом
  - Пользователь должен иметь возможность выбирать уровень
  - Пользователь должен иметь возможность выбирать задачу
  - Пользователь должен иметь возможность фильтровать задачи по темам
  - Пользователь должен иметь возможность просматривать Rules & Details
  - Пользователь должен иметь возможность пользоваться чатом на главной странице
  - Пользователь должен иметь возможность отправлять и получать сообщения в чате в режиме реального времени
  - Пользователь должен иметь возможность просматривать таблицу лидеров (Leaderboard)
  - Пользователь должен иметь возможность просматривать профиль других игроков
  - Пользователь должен иметь возможность просматривать историю своих игр
  - Пользователь должен иметь возможность наблюдать за чужими играми (spectate mode)
  - Код пользователя должен автоматически проверяться системой во время битвы
  - Система должна определять победителя по результатам проверки кода
  - Пользователь должен получать уведомления (внутренние) о начале игры, окончании, приглашениях
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Чат должен работать без необходимости обновлять страницу
  - Сообщения в чате должны отображаться сразу после отправки
  - Все элементы интерфейса должны отображаться корректно на разных размерах экранов
